sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - pwd
  - ls -la

install:
  - cd api && npm install
  - cd ../client && npm install

script:
  - cd ../api && npm test
  - cd ../client && npm run build
  - docker build -t ushagour/client ./client

after_success:
  - docker push ushagour/client
