sudo: required
services:
  - docker

before_install:
  - pwd
  - ls -la

install:
  - cd api && npm install
  - cd ../client && npm install

script:
  - cd ../api && npm test
  - cd ../client && npm run build

after_success:
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Build Docker image and tag it properly
  - docker build -t $DOCKER_USERNAME/simpletaskmanager-client ./client
  # Push the image to Docker Hub
  - docker push $DOCKER_USERNAME/simpletaskmanager-client
