sudo: required

services:
  - docker

install:
  - cd api && npm install && cd ..
  - cd client && npm install && cd ..

script:
  - cd api && npm test && cd ..
  - cd client && npm run build && cd ..

after_success:
  - docker build -t ushagour/api ./api
  - docker build -t ushagour/client ./client
