version: "3"
services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/tasksdb

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
